### ISSUE TITLE
findimports library action request

### ISSUE THREAD

**Issue by dg-pb** [timhoffm/using-matplotlib#1]
Hi Tim,

I could not find your contact information in public domain so I hope you don't mind I drop you a message via this issue.

There is an attempt to change license of `findimports` library from GPL to MIT and approval of contributors is needed.

If you could have a look at https://github.com/mgedmin/findimports/issues/27
it would be much appreciated.

Regards,
DG

**Comment by timhoffm** [comment]
Solved.
